language: node_js
node_js:
        "stable"
before_install:
        "nvm install-latest-npm"
install:
        "npm install --prefix src_client"
script:
        - 'npm test --prefix src_client'
env:
        - REACT=16
