export const ADD_BUDGET = 'ADD_BUDGET';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const ADD_BUDGET_EDIT = 'ADD_BUDGET_EDIT';
export const CLEAR_EDITED_BUDGET = 'CLEAR_EDITED_BUDGET ';
export const UPDATE_EXISTING_BUDGET = 'UPDATE_EXISTING_BUDGET ';
export const REMOVE_BUDGET = 'REMOVE_BUDGET';
